apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend0113
  name: backend0113
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend0113
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend0113
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - name: mysqldata
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: claim-03833
